app/iht/views/registration/deceased/deceased_address_question.scala.html, test/iht/views/registration/YesNoQuestionViewBehaviour.scala, test/iht/views/registration/deceased/DeceasedAddressQuestionViewTest.scala
Don't merge until IHT-4114 has been merged.
=> Iht 4116 ATR - Deceased Address Question

app/iht/views/application/gift/gifts_sidebar.scala.html, app/iht/views/application/gift/seven_years_gift_values.scala.html, conf/messages, test/iht/controllers/application/gifts/GivenAwayControllerTest.scala, test/iht/controllers/application/gifts/SevenYearsGiftsValuesControllerTest.scala, test/iht/models/application/ApplicationDetailsTest.scala, test/iht/testhelpers/CommonBuilder.scala, test/iht/utils/DeclarationHelperTest.scala, test/iht/views/GenericNonSubmittablePageBehaviour.scala, test/iht/views/ViewTestHelper.scala, test/iht/views/application/ApplicationPageBehaviour.scala, test/iht/views/application/assets/properties/PropertiesOverviewViewTest.scala, test/iht/views/application/assets/properties/PropertyDetailsOverviewViewTest.scala, test/iht/views/application/gifts/GiftsOverviewViewTest.scala, test/iht/views/application/gifts/GiftsSidebarViewTest.scala, test/iht/views/application/gifts/SevenYearsGiftValuesViewTest.scala, test/iht/views/application/gifts/SevenYearsGivenInLast7YearsViewTest.scala, test/iht/views/application/gifts/SevenYearsToTrustViewTest.scala, test/iht/views/application/gifts/WithReservationOfBenefitViewTest.scala
Only guidance pages left to do in part 3
=> Iht 4207 Gifts unit tests part 2

test/iht/testhelpers/MessagesTidierTest.scala
=> IHT-LANG-UNIT-TEST-FIX Fix unit tests

app/iht/views/application/declaration/checked_everything_question.scala.html, conf/messages.en, test/iht/views/application/declaration/CheckedEverythingViewTest.scala
…of continue to declaration page
=> IHT-4648 Remove the deceased's name from the browser title of continue to declaration page

app/assets/stylesheets/partials/_typography.scss, app/assets/stylesheets/partials/_utilities.scss, app/iht/views/ihtHelpers/custom/progressive_disclosure.scala.html, app/iht/views/iht_main_template.scala.html, conf/messages.en, test/iht/views/IhtMainTemplateTest.scala
=> Iht 4487 Add contact us link

app/assets/javascripts/jquery-ui.js, app/iht/controllers/application/EstateController.scala, app/iht/controllers/application/exemptions/qualifyingBody/QualifyingBodiesOverviewController.scala, app/iht/controllers/application/exemptions/qualifyingBody/QualifyingBodyNameController.scala, app/iht/models/application/ApplicationDetails.scala, app/iht/views/application/exemption/qualifyingBody/qualifying_bodies_overview.scala.html, conf/app.routes, test/iht/controllers/application/exemptions/charity/CharityNameControllerTest.scala, test/iht/controllers/application/exemptions/charity/CharityNumberControllerTest.scala, test/iht/controllers/application/exemptions/qualifyingBody/QualifyingBodyNameControllerTest.scala, test/iht/controllers/application/exemptions/qualifyingBody/QualifyingBodyValueControllerTest.scala, test/iht/controllers/registration/CompletedRegistrationControllerTest.scala, test/iht/controllers/registration/deceased/DeceasedAddressQuestionControllerTest.scala, test/iht/viewmodels/application/overview/OtherDetailsSectionViewModelTest.scala, test/iht/viewmodels/application/overview/ReducingEstateValueSectionViewModelTest.scala, test/iht/views/application/IhtKickoutApplicationViewTest.scala
Comments added to ticket about potential refactoring.
=> IHT-4271 - Remove TODOs

app/iht/models/des/IHTReturn.scala, app/iht/utils/pdf/PdfFormatter.scala, test/iht/models/des/IHTReturnTest.scala, test/iht/resources/IhtReturn.scala, test/iht/testhelpers/IHTReturnTestHelper.scala
Note the stub project has changed too
=> Iht 4813 PDF exemptions value not matching value displayed in service

app/iht/constants/IhtProperties.scala, app/iht/controllers/DeadlinesController.scala, app/iht/controllers/application/KickoutController.scala, app/iht/controllers/filter/FilterController.scala, app/iht/utils/CommonHelper.scala, app/iht/views/deadlines.scala.html, app/iht/views/deadlines_application.scala.html, app/iht/views/deadlines_registration.scala.html, app/iht/views/filter/use_iht400.scala.html, conf/app.routes, conf/iht.properties, conf/messages.en, test/iht/controllers/application/KickoutControllerTest.scala, test/iht/testhelpers/TestHelper.scala, test/iht/views/DeadlinesApplicationViewTest.scala, test/iht/views/DeadlinesRegistrationViewTest.scala, test/iht/views/DeadlinesViewTest.scala, test/iht/views/filter/UseIHT400ViewTest.scala
Can review but don't merge till Welsh content is received and integrated.
=> Iht 5139 IHT - Flat content iteration Deadlines for reporting and paying tax

app/iht/views/ihtHelpers/standard/input_yes_no_radio_group.scala.html, app/iht/views/iht_main_template.scala.html
=> Iht 5217 Implement GA events for field level validation errors 

app/assets/javascripts/show-hide-content.js, app/iht/views/application/asset/properties/property_ownership.scala.html, app/iht/views/application/asset/properties/property_tenure.scala.html, app/iht/views/application/asset/properties/property_type.scala.html, app/iht/views/filter/domicile.scala.html, app/iht/views/filter/estimate.scala.html, app/iht/views/filter/filter_jointly_owned.scala.html, app/iht/views/filter/filter_view.scala.html, app/iht/views/ihtHelpers/standard/input_radio_group.scala.html, app/iht/views/ihtHelpers/standard/input_radio_group_with_hints.scala.html, app/iht/views/ihtHelpers/standard/input_yes_no_radio_group.scala.html, app/iht/views/registration/deceased/about_deceased.scala.html, test/iht/views/ViewTestHelper.scala
Changes include:
- Update 3 radio button helpers
- Update show-hide-content.js to work with the updates in markup
- Remove labelAfter, because it's unnecessary and not being used anyhow
=> Update radio buttons to the latest version

project/FrontendBuild.scala
Updated Bootstrap and updated the ports and protocols within the app-config-base.
=> DL-1097 Updated Bootstrap

app/iht/views/ihtHelpers/custom/progressive_disclosure.scala.html
Fixing issue with progressive disclosure not being underlined for Get help with this service
tests and acceptance tests run successfully
=> DL-798fixel fixing underline issue for Get help with this service

app/iht/views/application/exemption/partner/partner_date_of_birth.scala.html, app/iht/views/application/tnrb/date_of_marriage.scala.html, app/iht/views/application/tnrb/deceased_widow_check_date.scala.html, app/iht/views/ihtHelpers/custom/progressive_disclosure.scala.html, app/iht/views/ihtHelpers/standard/date_fields.scala.html, app/iht/views/ihtHelpers/standard/date_input.scala.html, app/iht/views/registration/deceased/deceased_date_of_death.scala.html
**Fix**
Fixing registration/date-of-death page to remove any html errors as part of validation.
=> DL-1371 initial changes to fix html issue for date related views

app/iht/config/ApplicationConfig.scala, app/iht/config/ApplicationGlobal.scala, app/iht/config/wiring.scala, app/iht/connector/CachingConnector.scala, app/iht/connector/CitizenDetailsConnector.scala, app/iht/connector/IdentityVerificationConnector.scala, app/iht/connector/IhtConnector.scala, app/iht/controllers/CustomLanguageController.scala, app/iht/controllers/application/ApplicationController.scala, app/iht/controllers/application/EstateController.scala, app/iht/controllers/application/assets/properties/PropertyTenureController.scala, app/iht/controllers/auth/IhtBaseController.scala, app/iht/forms/ApplicationForms.scala, app/iht/modules/Module.scala, app/iht/utils/AuthHelper.scala, project/FrontendBuild.scala, project/plugins.sbt
**Upgrade**
* Upgraded IHT to play 2.5.19.
=> DL-1469 IHT 2.5.19 upgrade

app/iht/modules/Module.scala
*Bug fix*
* Fixed missing bind of AgentController
=> DL-1502 Fixed missing agent controller binding

app/iht/modules/Module.scala
*Bug fix* 
* Amended two missing bindings in IHT FE
=> DL-1502 Amended two missing bindings in IHT FE

app/iht/controllers/IVUpliftFailureController.scala, app/iht/controllers/application/tnrb/DeceasedWidowCheckDateController.scala, app/iht/utils/tnrb/TnrbHelper.scala
**Bug fix**
* Amended missing lazy val on IHT Frontend. This issue was causing some of the pages to redirect to an incorrect URL, causing acceptance tests to fail.
=> DL-1646-fix Amended lazy val

.github/CONTRIBUTING.md, .github/ISSUE_TEMPLATE.md, .github/PULL_REQUEST_TEMPLATE.md, app/iht/config/IHTErrorHandler.scala, app/iht/views/iht_not_found_template.scala.html, project/FrontendBuild.scala, project/plugins.sbt
**Bug fix**
Template created to show on 404 not found as original error page had been overwritten, also dependencies updated and github files added.
Unable to run acceptance tests locally on master or on branch so needs review.
*Reviewee* Andrew
*Reviewer* Graham Cook
=>  DL-1144 - New template for 404 Not found

README.md, app/iht/controllers/application/debts/MortgageValueController.scala, project/FrontendBuild.scala, project/plugins.sbt
**Bug fix ** 
Removed an error message that was clogging up our logs. The message did not actually indicate an error with the service.
*Reviewee* (Ben)
- N/A  I've included appropriate tests with any code I've added (Unit, Integration, Acceptance etc.)
*Reviewer* (@grahampaulcook )
=> DL-2150: Removing unnecessary/unwanted error log

app/iht/config/ApplicationConfig.scala, app/iht/views/iht_main_template.scala.html, conf/application.conf
Added Google Tag Manager integration to IHT Frontend, in accordance with issue DL-1411.
Stephen
=> added Google Tag Manager functionality

conf/application.conf
The previously stubbed Google Tag Manager ID from epic issue DL-1411 has been replaced with a valid ID.
*Stephen*
=> DL-2584 - Add GTM ID to IHT-Frontend

conf/messages.cy
=> DL-2806 - Welsh translation of IV error page

README.md, app/assets/stylesheets/partials/_timeout-dialog.scss, app/iht/views/iht_main_template.scala.html
=> DL-3896 - iht-frontend timeout dialog doesn't appear

app/iht/config/ApplicationConfig.scala, app/iht/views/iht_main_template.scala.html, conf/application.conf
=> Removed GA and added tracking consent

README.md, app/iht/events/IhtAuditEvent.scala, conf/application.conf, it/utils/IntegrationBaseSpec.scala, project/AppDependencies.scala, project/plugins.sbt, test/iht/forms/FormTestHelper.scala
**Bug fix / New feature** (delete as appropriate)
Please include a summary / description of the change and which issue it fixes.  Include any relevant user needs, context or links to other PRs related to this PR (eg. acceptance tests, environment config).
- []  I've confirmed that every effort has been made to commit high quality, clean code and I have executed relevant static analyses to be sure
- []  I've confirmed appropriate tests has been included with any code added (Unit, Integration, Acceptance etc.)
=> DL-5483 - bootstrap uplift

build.sbt, project/AppDependencies.scala, project/plugins.sbt
=> DL-5585 Auth client upgrade

project/plugins.sbt
=> DL-5758 - Amended plugins.sbt

app/iht/controllers/registration/CompletedRegistrationController.scala, app/iht/controllers/registration/DuplicateRegistrationController.scala, app/iht/controllers/registration/KickoutRegController.scala, app/iht/controllers/registration/applicant/ApplicantAddressController.scala, app/iht/controllers/registration/deceased/AboutDeceasedController.scala, app/iht/controllers/registration/executor/CoExecutorPersonalDetailsController.scala, app/iht/controllers/registration/executor/DeleteCoExecutorController.scala, app/iht/controllers/registration/executor/OtherPersonsAddressController.scala, project/AppDependencies.scala, test/iht/views/ViewTestHelper.scala
=> DL-5332 Removing references to whitelist

app/iht/views/application/overview/estate_overview.scala.html, app/iht/views/application/overview/threshold_section.scala.html, test/iht/views/application/overview/EstateOverviewViewTest.scala
Please include a summary / description of the change and which issue it fixes.  Include any relevant user needs, context or links to other PRs related to this PR (eg. acceptance tests, environment config).
*Stephen*
=> DL-6736 - Removed report deadline

app/iht/constants/Constants.scala, app/iht/constants/FieldMappings.scala, app/iht/controllers/filter/AnyAssetsController.scala, app/iht/controllers/filter/EstimateController.scala, app/iht/controllers/filter/NoAssetsController.scala, app/iht/forms/FilterForms.scala, app/iht/modules/Module.scala, app/iht/views/filter/any_assets.scala.html, app/iht/views/filter/no_assets.scala.html, app/iht/views/filter/previous_answers.scala.html, app/iht/views/filter/use_service.scala.html, conf/app.routes, conf/messages.cy, conf/messages.en, test/iht/controllers/filter/AnyAssetsControllerTest.scala, test/iht/controllers/filter/NoAssetsControllerTest.scala, test/iht/views/filter/AnyAssetsViewTest.scala, test/iht/views/filter/NoAssetsViewTest.scala
DL-6683
New pages added:
- **/any-assets-to-declare**
- **/no-assets**
=> DL-6683 Declaring no assets added to journey
